import Head from "next/head";
import dynamic from "next/dynamic";

const Homepage = dynamic(() => import("@/components/homepage/Homepage"));

export default function Home() {
  return (
    <>
      <Head>
        <title>Joseph McMahon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="icon"
          href="/biggerIcon.png"
          type="image/png"
          sizes="180x180"
        />
      </Head>
      <Homepage />
    </>
  );
}
